// Code generated by fino2. DO NOT EDIT.
// Rerunning fino will overwrite this file.
// Version: v0.1.0
// Version Date:

package middleware

import (
	"github.com/chaos-io/gokit/middleware"

	// this service api
	"github.com/liankui/OpenBambuAPI/armory/backend/modules/armory-server/api/endpoint"
	"github.com/liankui/OpenBambuAPI/armory/backend/modules/armory-server/infra/metrics"
)

func wrapInstrumenting(in endpoint.Endpoints, options map[string]any) {
	count := metrics.NewCount()
	latency := metrics.NewLatency()
	if count == nil || latency == nil {
		return
	}

	in.LoginEndpoint = middleware.Instrumenting(latency.With("method", "Login"), count.With("method", "Login"))(in.LoginEndpoint)
	in.RefreshTokenEndpoint = middleware.Instrumenting(latency.With("method", "RefreshToken"), count.With("method", "RefreshToken"))(in.RefreshTokenEndpoint)
	in.ListMyMessagesEndpoint = middleware.Instrumenting(latency.With("method", "ListMyMessages"), count.With("method", "ListMyMessages"))(in.ListMyMessagesEndpoint)
	in.ListMyTasksEndpoint = middleware.Instrumenting(latency.With("method", "ListMyTasks"), count.With("method", "ListMyTasks"))(in.ListMyTasksEndpoint)
	in.GetSlicerResourcesEndpoint = middleware.Instrumenting(latency.With("method", "GetSlicerResources"), count.With("method", "GetSlicerResources"))(in.GetSlicerResourcesEndpoint)
	in.ListUserDevicesEndpoint = middleware.Instrumenting(latency.With("method", "ListUserDevices"), count.With("method", "ListUserDevices"))(in.ListUserDevicesEndpoint)
	in.GetPrintStatusEndpoint = middleware.Instrumenting(latency.With("method", "GetPrintStatus"), count.With("method", "GetPrintStatus"))(in.GetPrintStatusEndpoint)
	in.GetTtcodeEndpoint = middleware.Instrumenting(latency.With("method", "GetTTCode"), count.With("method", "GetTTCode"))(in.GetTtcodeEndpoint)
}
