// Code generated by fino2. DO NOT EDIT.
// Rerunning fino will overwrite this file.
// Version: v0.1.0
// Version Date:

package middleware

import (
	"github.com/chaos-io/gokit/tracing"
	"go.opentelemetry.io/otel/trace"

	// this service api
	"github.com/liankui/OpenBambuAPI/armory/backend/modules/armory-server/api/endpoint"
)

func wrapTracer(in endpoint.Endpoints, options map[string]any) {
	var tracer trace.Tracer
	if value, ok := options["tracer"]; ok && value != nil {
		tracer = value.(trace.Tracer)
	} else {
		return
	}

	in.LoginEndpoint = tracing.TraceServer(tracer, "Login")(in.LoginEndpoint)
	in.RefreshTokenEndpoint = tracing.TraceServer(tracer, "RefreshToken")(in.RefreshTokenEndpoint)
	in.ListMyMessagesEndpoint = tracing.TraceServer(tracer, "ListMyMessages")(in.ListMyMessagesEndpoint)
	in.ListMyTasksEndpoint = tracing.TraceServer(tracer, "ListMyTasks")(in.ListMyTasksEndpoint)
	in.GetSlicerResourcesEndpoint = tracing.TraceServer(tracer, "GetSlicerResources")(in.GetSlicerResourcesEndpoint)
	in.ListUserDevicesEndpoint = tracing.TraceServer(tracer, "ListUserDevices")(in.ListUserDevicesEndpoint)
	in.GetPrintStatusEndpoint = tracing.TraceServer(tracer, "GetPrintStatus")(in.GetPrintStatusEndpoint)
	in.GetTtcodeEndpoint = tracing.TraceServer(tracer, "GetTTCode")(in.GetTtcodeEndpoint)
}
