// Code generated by fino2. DO NOT EDIT.
// Rerunning fino will overwrite this file.
// Version: v0.1.0
// Version Date:

package middleware

import (
	"github.com/chaos-io/gokit/middleware"

	// this service api
	"github.com/liankui/OpenBambuAPI/armory/backend/modules/armory-server/api/endpoint"
)

func wrapValidator(in endpoint.Endpoints, options map[string]any) {
	if value, ok := options["validator"]; !ok || value == nil {
		return
	}

	in.LoginEndpoint = middleware.ValidatorMW()(in.LoginEndpoint)
	in.RefreshTokenEndpoint = middleware.ValidatorMW()(in.RefreshTokenEndpoint)
	in.ListMyMessagesEndpoint = middleware.ValidatorMW()(in.ListMyMessagesEndpoint)
	in.ListMyTasksEndpoint = middleware.ValidatorMW()(in.ListMyTasksEndpoint)
	in.GetSlicerResourcesEndpoint = middleware.ValidatorMW()(in.GetSlicerResourcesEndpoint)
	in.ListUserDevicesEndpoint = middleware.ValidatorMW()(in.ListUserDevicesEndpoint)
	in.GetPrintStatusEndpoint = middleware.ValidatorMW()(in.GetPrintStatusEndpoint)
	in.GetTtcodeEndpoint = middleware.ValidatorMW()(in.GetTtcodeEndpoint)
}
