// Code generated by fino2. DO NOT EDIT.
// Rerunning fino will overwrite this file.
// Version: v0.1.0
// Version Date:

package grpc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"github.com/chaos-io/gokit/tracing"
	"github.com/go-kit/kit/log"
	grpctransport "github.com/go-kit/kit/transport/grpc"
	"go.opentelemetry.io/otel/trace"
	"google.golang.org/grpc/metadata"

	// this service api
	"github.com/liankui/OpenBambuAPI/armory/backend/modules/armory-server/api/endpoint"
	pb "github.com/liankui/OpenBambuAPI/armory/go/armory/v1"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC ArmoryServer.
func MakeGRPCServer(endpoints endpoint.Endpoints, tracer trace.Tracer, logger log.Logger) pb.ArmoryServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
		grpctransport.ServerErrorLogger(logger),
	}

	addTracerOption := func(methodName string) []grpctransport.ServerOption {
		if tracer != nil {
			return append(serverOptions, grpctransport.ServerBefore(tracing.GRPCToContext(tracer, methodName)))
		}
		return serverOptions
	}

	// Armory
	return &grpcServer{
		login: grpctransport.NewServer(
			endpoints.LoginEndpoint,
			DecodeGRPCLoginRequest,
			EncodeGRPCLoginResponse,
			addTracerOption("Login")...,
		), refreshToken: grpctransport.NewServer(
			endpoints.RefreshTokenEndpoint,
			DecodeGRPCRefreshTokenRequest,
			EncodeGRPCRefreshTokenResponse,
			addTracerOption("RefreshToken")...,
		), listMyMessages: grpctransport.NewServer(
			endpoints.ListMyMessagesEndpoint,
			DecodeGRPCListMyMessagesRequest,
			EncodeGRPCListMyMessagesResponse,
			addTracerOption("ListMyMessages")...,
		), listMyTasks: grpctransport.NewServer(
			endpoints.ListMyTasksEndpoint,
			DecodeGRPCListMyTasksRequest,
			EncodeGRPCListMyTasksResponse,
			addTracerOption("ListMyTasks")...,
		), getSlicerResources: grpctransport.NewServer(
			endpoints.GetSlicerResourcesEndpoint,
			DecodeGRPCGetSlicerResourcesRequest,
			EncodeGRPCGetSlicerResourcesResponse,
			addTracerOption("GetSlicerResources")...,
		), listUserDevices: grpctransport.NewServer(
			endpoints.ListUserDevicesEndpoint,
			DecodeGRPCListUserDevicesRequest,
			EncodeGRPCListUserDevicesResponse,
			addTracerOption("ListUserDevices")...,
		), getPrintStatus: grpctransport.NewServer(
			endpoints.GetPrintStatusEndpoint,
			DecodeGRPCGetPrintStatusRequest,
			EncodeGRPCGetPrintStatusResponse,
			addTracerOption("GetPrintStatus")...,
		), getTtcode: grpctransport.NewServer(
			endpoints.GetTtcodeEndpoint,
			DecodeGRPCGetTtcodeRequest,
			EncodeGRPCGetTtcodeResponse,
			addTracerOption("GetTTCode")...,
		),
	}
}

// grpcServer implements the ArmoryServer interface
type grpcServer struct {
	pb.UnimplementedArmoryServer

	login              grpctransport.Handler
	refreshToken       grpctransport.Handler
	listMyMessages     grpctransport.Handler
	listMyTasks        grpctransport.Handler
	getSlicerResources grpctransport.Handler
	listUserDevices    grpctransport.Handler
	getPrintStatus     grpctransport.Handler
	getTtcode          grpctransport.Handler
}

// Methods for grpcServer to implement ArmoryServer interface

func (s *grpcServer) Login(ctx context.Context, req *pb.LoginRequest) (*pb.LoginResponse, error) {
	_, rep, err := s.login.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.LoginResponse), nil
}

func (s *grpcServer) RefreshToken(ctx context.Context, req *pb.RefreshTokenRequest) (*pb.RefreshTokenResponse, error) {
	_, rep, err := s.refreshToken.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.RefreshTokenResponse), nil
}

func (s *grpcServer) ListMyMessages(ctx context.Context, req *pb.ListMyMessagesRequest) (*pb.ListMyMessagesResponse, error) {
	_, rep, err := s.listMyMessages.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.ListMyMessagesResponse), nil
}

func (s *grpcServer) ListMyTasks(ctx context.Context, req *pb.ListMyTasksRequest) (*pb.ListMyTasksResponse, error) {
	_, rep, err := s.listMyTasks.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.ListMyTasksResponse), nil
}

func (s *grpcServer) GetSlicerResources(ctx context.Context, req *pb.GetSlicerResourcesRequest) (*pb.GetSlicerResourcesResponse, error) {
	_, rep, err := s.getSlicerResources.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.GetSlicerResourcesResponse), nil
}

func (s *grpcServer) ListUserDevices(ctx context.Context, req *pb.ListUserDevicesRequest) (*pb.ListUserDevicesResponse, error) {
	_, rep, err := s.listUserDevices.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.ListUserDevicesResponse), nil
}

func (s *grpcServer) GetPrintStatus(ctx context.Context, req *pb.GetPrintStatusRequest) (*pb.GetPrintStatusResponse, error) {
	_, rep, err := s.getPrintStatus.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.GetPrintStatusResponse), nil
}

func (s *grpcServer) GetTtcode(ctx context.Context, req *pb.GetTtcodeRequest) (*pb.GetTtcodeResponse, error) {
	_, rep, err := s.getTtcode.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.GetTtcodeResponse), nil
}

// Server Decode

// DecodeGRPCLoginRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC Login request to a user-domain Login request. Primarily useful in a server.
func DecodeGRPCLoginRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.LoginRequest)
	return req, nil
}

// DecodeGRPCRefreshTokenRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC RefreshToken request to a user-domain RefreshToken request. Primarily useful in a server.
func DecodeGRPCRefreshTokenRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.RefreshTokenRequest)
	return req, nil
}

// DecodeGRPCListMyMessagesRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC ListMyMessages request to a user-domain ListMyMessages request. Primarily useful in a server.
func DecodeGRPCListMyMessagesRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.ListMyMessagesRequest)
	return req, nil
}

// DecodeGRPCListMyTasksRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC ListMyTasks request to a user-domain ListMyTasks request. Primarily useful in a server.
func DecodeGRPCListMyTasksRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.ListMyTasksRequest)
	return req, nil
}

// DecodeGRPCGetSlicerResourcesRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC GetSlicerResources request to a user-domain GetSlicerResources request. Primarily useful in a server.
func DecodeGRPCGetSlicerResourcesRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.GetSlicerResourcesRequest)
	return req, nil
}

// DecodeGRPCListUserDevicesRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC ListUserDevices request to a user-domain ListUserDevices request. Primarily useful in a server.
func DecodeGRPCListUserDevicesRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.ListUserDevicesRequest)
	return req, nil
}

// DecodeGRPCGetPrintStatusRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC GetPrintStatus request to a user-domain GetPrintStatus request. Primarily useful in a server.
func DecodeGRPCGetPrintStatusRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.GetPrintStatusRequest)
	return req, nil
}

// DecodeGRPCGetTtcodeRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC GetTtcode request to a user-domain GetTtcode request. Primarily useful in a server.
func DecodeGRPCGetTtcodeRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.GetTtcodeRequest)
	return req, nil
}

// Server Encode

// EncodeGRPCLoginResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain Login response to a gRPC Login reply. Primarily useful in a server.
func EncodeGRPCLoginResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.LoginResponse)
	return resp, nil
}

// EncodeGRPCRefreshTokenResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain RefreshToken response to a gRPC RefreshToken reply. Primarily useful in a server.
func EncodeGRPCRefreshTokenResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.RefreshTokenResponse)
	return resp, nil
}

// EncodeGRPCListMyMessagesResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain ListMyMessages response to a gRPC ListMyMessages reply. Primarily useful in a server.
func EncodeGRPCListMyMessagesResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.ListMyMessagesResponse)
	return resp, nil
}

// EncodeGRPCListMyTasksResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain ListMyTasks response to a gRPC ListMyTasks reply. Primarily useful in a server.
func EncodeGRPCListMyTasksResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.ListMyTasksResponse)
	return resp, nil
}

// EncodeGRPCGetSlicerResourcesResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain GetSlicerResources response to a gRPC GetSlicerResources reply. Primarily useful in a server.
func EncodeGRPCGetSlicerResourcesResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.GetSlicerResourcesResponse)
	return resp, nil
}

// EncodeGRPCListUserDevicesResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain ListUserDevices response to a gRPC ListUserDevices reply. Primarily useful in a server.
func EncodeGRPCListUserDevicesResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.ListUserDevicesResponse)
	return resp, nil
}

// EncodeGRPCGetPrintStatusResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain GetPrintStatus response to a gRPC GetPrintStatus reply. Primarily useful in a server.
func EncodeGRPCGetPrintStatusResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.GetPrintStatusResponse)
	return resp, nil
}

// EncodeGRPCGetTtcodeResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain GetTtcode response to a gRPC GetTtcode reply. Primarily useful in a server.
func EncodeGRPCGetTtcodeResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.GetTtcodeResponse)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
