// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/liankui/OpenBambuAPI/armory/backend/infra/http (interfaces: IClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	http "github.com/liankui/OpenBambuAPI/armory/backend/infra/http"
)

// MockIClient is a mock of IClient interface.
type MockIClient struct {
	ctrl     *gomock.Controller
	recorder *MockIClientMockRecorder
}

// MockIClientMockRecorder is the mock recorder for MockIClient.
type MockIClientMockRecorder struct {
	mock *MockIClient
}

// NewMockIClient creates a new mock instance.
func NewMockIClient(ctrl *gomock.Controller) *MockIClient {
	mock := &MockIClient{ctrl: ctrl}
	mock.recorder = &MockIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClient) EXPECT() *MockIClientMockRecorder {
	return m.recorder
}

// DoHTTPRequest mocks base method.
func (m *MockIClient) DoHTTPRequest(arg0 context.Context, arg1 *http.RequestParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoHTTPRequest", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DoHTTPRequest indicates an expected call of DoHTTPRequest.
func (mr *MockIClientMockRecorder) DoHTTPRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoHTTPRequest", reflect.TypeOf((*MockIClient)(nil).DoHTTPRequest), arg0, arg1)
}
