// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: armory/v1/armory.proto

package armory

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Armory_Login_FullMethodName              = "/armory.v1.Armory/Login"
	Armory_RefreshToken_FullMethodName       = "/armory.v1.Armory/RefreshToken"
	Armory_ListMyMessages_FullMethodName     = "/armory.v1.Armory/ListMyMessages"
	Armory_ListMyTasks_FullMethodName        = "/armory.v1.Armory/ListMyTasks"
	Armory_GetSlicerResources_FullMethodName = "/armory.v1.Armory/GetSlicerResources"
	Armory_ListUserDevices_FullMethodName    = "/armory.v1.Armory/ListUserDevices"
	Armory_GetPrintStatus_FullMethodName     = "/armory.v1.Armory/GetPrintStatus"
	Armory_GetTTCode_FullMethodName          = "/armory.v1.Armory/GetTTCode"
)

// ArmoryClient is the client API for Armory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArmoryClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	ListMyMessages(ctx context.Context, in *ListMyMessagesRequest, opts ...grpc.CallOption) (*ListMyMessagesResponse, error)
	ListMyTasks(ctx context.Context, in *ListMyTasksRequest, opts ...grpc.CallOption) (*ListMyTasksResponse, error)
	GetSlicerResources(ctx context.Context, in *GetSlicerResourcesRequest, opts ...grpc.CallOption) (*GetSlicerResourcesResponse, error)
	ListUserDevices(ctx context.Context, in *ListUserDevicesRequest, opts ...grpc.CallOption) (*ListUserDevicesResponse, error)
	GetPrintStatus(ctx context.Context, in *GetPrintStatusRequest, opts ...grpc.CallOption) (*GetPrintStatusResponse, error)
	GetTTCode(ctx context.Context, in *GetTTCodeRequest, opts ...grpc.CallOption) (*GetTTCodeResponse, error)
}

type armoryClient struct {
	cc grpc.ClientConnInterface
}

func NewArmoryClient(cc grpc.ClientConnInterface) ArmoryClient {
	return &armoryClient{cc}
}

func (c *armoryClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, Armory_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *armoryClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, Armory_RefreshToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *armoryClient) ListMyMessages(ctx context.Context, in *ListMyMessagesRequest, opts ...grpc.CallOption) (*ListMyMessagesResponse, error) {
	out := new(ListMyMessagesResponse)
	err := c.cc.Invoke(ctx, Armory_ListMyMessages_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *armoryClient) ListMyTasks(ctx context.Context, in *ListMyTasksRequest, opts ...grpc.CallOption) (*ListMyTasksResponse, error) {
	out := new(ListMyTasksResponse)
	err := c.cc.Invoke(ctx, Armory_ListMyTasks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *armoryClient) GetSlicerResources(ctx context.Context, in *GetSlicerResourcesRequest, opts ...grpc.CallOption) (*GetSlicerResourcesResponse, error) {
	out := new(GetSlicerResourcesResponse)
	err := c.cc.Invoke(ctx, Armory_GetSlicerResources_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *armoryClient) ListUserDevices(ctx context.Context, in *ListUserDevicesRequest, opts ...grpc.CallOption) (*ListUserDevicesResponse, error) {
	out := new(ListUserDevicesResponse)
	err := c.cc.Invoke(ctx, Armory_ListUserDevices_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *armoryClient) GetPrintStatus(ctx context.Context, in *GetPrintStatusRequest, opts ...grpc.CallOption) (*GetPrintStatusResponse, error) {
	out := new(GetPrintStatusResponse)
	err := c.cc.Invoke(ctx, Armory_GetPrintStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *armoryClient) GetTTCode(ctx context.Context, in *GetTTCodeRequest, opts ...grpc.CallOption) (*GetTTCodeResponse, error) {
	out := new(GetTTCodeResponse)
	err := c.cc.Invoke(ctx, Armory_GetTTCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArmoryServer is the server API for Armory service.
// All implementations must embed UnimplementedArmoryServer
// for forward compatibility
type ArmoryServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	ListMyMessages(context.Context, *ListMyMessagesRequest) (*ListMyMessagesResponse, error)
	ListMyTasks(context.Context, *ListMyTasksRequest) (*ListMyTasksResponse, error)
	GetSlicerResources(context.Context, *GetSlicerResourcesRequest) (*GetSlicerResourcesResponse, error)
	ListUserDevices(context.Context, *ListUserDevicesRequest) (*ListUserDevicesResponse, error)
	GetPrintStatus(context.Context, *GetPrintStatusRequest) (*GetPrintStatusResponse, error)
	GetTTCode(context.Context, *GetTTCodeRequest) (*GetTTCodeResponse, error)
	mustEmbedUnimplementedArmoryServer()
}

// UnimplementedArmoryServer must be embedded to have forward compatible implementations.
type UnimplementedArmoryServer struct {
}

func (UnimplementedArmoryServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedArmoryServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedArmoryServer) ListMyMessages(context.Context, *ListMyMessagesRequest) (*ListMyMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMyMessages not implemented")
}
func (UnimplementedArmoryServer) ListMyTasks(context.Context, *ListMyTasksRequest) (*ListMyTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMyTasks not implemented")
}
func (UnimplementedArmoryServer) GetSlicerResources(context.Context, *GetSlicerResourcesRequest) (*GetSlicerResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSlicerResources not implemented")
}
func (UnimplementedArmoryServer) ListUserDevices(context.Context, *ListUserDevicesRequest) (*ListUserDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserDevices not implemented")
}
func (UnimplementedArmoryServer) GetPrintStatus(context.Context, *GetPrintStatusRequest) (*GetPrintStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrintStatus not implemented")
}
func (UnimplementedArmoryServer) GetTTCode(context.Context, *GetTTCodeRequest) (*GetTTCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTTCode not implemented")
}
func (UnimplementedArmoryServer) mustEmbedUnimplementedArmoryServer() {}

// UnsafeArmoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArmoryServer will
// result in compilation errors.
type UnsafeArmoryServer interface {
	mustEmbedUnimplementedArmoryServer()
}

func RegisterArmoryServer(s grpc.ServiceRegistrar, srv ArmoryServer) {
	s.RegisterService(&Armory_ServiceDesc, srv)
}

func _Armory_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArmoryServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Armory_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArmoryServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Armory_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArmoryServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Armory_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArmoryServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Armory_ListMyMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArmoryServer).ListMyMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Armory_ListMyMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArmoryServer).ListMyMessages(ctx, req.(*ListMyMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Armory_ListMyTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArmoryServer).ListMyTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Armory_ListMyTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArmoryServer).ListMyTasks(ctx, req.(*ListMyTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Armory_GetSlicerResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSlicerResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArmoryServer).GetSlicerResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Armory_GetSlicerResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArmoryServer).GetSlicerResources(ctx, req.(*GetSlicerResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Armory_ListUserDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArmoryServer).ListUserDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Armory_ListUserDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArmoryServer).ListUserDevices(ctx, req.(*ListUserDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Armory_GetPrintStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrintStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArmoryServer).GetPrintStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Armory_GetPrintStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArmoryServer).GetPrintStatus(ctx, req.(*GetPrintStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Armory_GetTTCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTTCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArmoryServer).GetTTCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Armory_GetTTCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArmoryServer).GetTTCode(ctx, req.(*GetTTCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Armory_ServiceDesc is the grpc.ServiceDesc for Armory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Armory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "armory.v1.Armory",
	HandlerType: (*ArmoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Armory_Login_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _Armory_RefreshToken_Handler,
		},
		{
			MethodName: "ListMyMessages",
			Handler:    _Armory_ListMyMessages_Handler,
		},
		{
			MethodName: "ListMyTasks",
			Handler:    _Armory_ListMyTasks_Handler,
		},
		{
			MethodName: "GetSlicerResources",
			Handler:    _Armory_GetSlicerResources_Handler,
		},
		{
			MethodName: "ListUserDevices",
			Handler:    _Armory_ListUserDevices_Handler,
		},
		{
			MethodName: "GetPrintStatus",
			Handler:    _Armory_GetPrintStatus_Handler,
		},
		{
			MethodName: "GetTTCode",
			Handler:    _Armory_GetTTCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "armory/v1/armory.proto",
}
