// Code generated by fino2. DO NOT EDIT.
// Rerunning fino will overwrite this file.
// Version: v0.1.0
// Version Date:

package endpoint

// This file contains methods to make individual endpoints from services,
// request and response types to serve those endpoints, as well as encoders and
// decoders for those types, for all of our supported transport serialization
// formats.

import (
	"context"
	"fmt"

	"github.com/go-kit/kit/endpoint"

	// this service api
	pb "github.com/liankui/OpenBambuAPI/armory/go/armory/v1"
)

// Endpoints collects all of the endpoints that compose an add service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
//
// In a server, it's useful for functions that need to operate on a per-endpoint
// basis. For example, you might pass an Endpoints to a function that produces
// an http.Handler, with each method (endpoint) wired up to a specific path. (It
// is probably a mistake in design to invoke the Service methods on the
// Endpoints struct in a server.)
//
// In a client, it's useful to collect individually constructed endpoints into a
// single type that implements the Service interface. For example, you might
// construct individual endpoints using transport/http.NewClient, combine them into an Endpoints, and return it to the caller as a Service.
type Endpoints struct {
	LoginEndpoint              endpoint.Endpoint
	RefreshTokenEndpoint       endpoint.Endpoint
	ListMyMessagesEndpoint     endpoint.Endpoint
	ListMyTasksEndpoint        endpoint.Endpoint
	GetSlicerResourcesEndpoint endpoint.Endpoint
	ListUserDevicesEndpoint    endpoint.Endpoint
	GetPrintStatusEndpoint     endpoint.Endpoint
	GetTtcodeEndpoint          endpoint.Endpoint
}

// Endpoints

func (e Endpoints) Login(ctx context.Context, in *pb.LoginRequest) (*pb.LoginResponse, error) {
	response, err := e.LoginEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.LoginResponse), nil
}

func (e Endpoints) RefreshToken(ctx context.Context, in *pb.RefreshTokenRequest) (*pb.RefreshTokenResponse, error) {
	response, err := e.RefreshTokenEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.RefreshTokenResponse), nil
}

func (e Endpoints) ListMyMessages(ctx context.Context, in *pb.ListMyMessagesRequest) (*pb.ListMyMessagesResponse, error) {
	response, err := e.ListMyMessagesEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.ListMyMessagesResponse), nil
}

func (e Endpoints) ListMyTasks(ctx context.Context, in *pb.ListMyTasksRequest) (*pb.ListMyTasksResponse, error) {
	response, err := e.ListMyTasksEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.ListMyTasksResponse), nil
}

func (e Endpoints) GetSlicerResources(ctx context.Context, in *pb.GetSlicerResourcesRequest) (*pb.GetSlicerResourcesResponse, error) {
	response, err := e.GetSlicerResourcesEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.GetSlicerResourcesResponse), nil
}

func (e Endpoints) ListUserDevices(ctx context.Context, in *pb.ListUserDevicesRequest) (*pb.ListUserDevicesResponse, error) {
	response, err := e.ListUserDevicesEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.ListUserDevicesResponse), nil
}

func (e Endpoints) GetPrintStatus(ctx context.Context, in *pb.GetPrintStatusRequest) (*pb.GetPrintStatusResponse, error) {
	response, err := e.GetPrintStatusEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.GetPrintStatusResponse), nil
}

func (e Endpoints) GetTtcode(ctx context.Context, in *pb.GetTtcodeRequest) (*pb.GetTtcodeResponse, error) {
	response, err := e.GetTtcodeEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.GetTtcodeResponse), nil
}

// Make Endpoints

func MakeLoginEndpoint(s pb.ArmoryServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.LoginRequest)
		v, err := s.Login(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeRefreshTokenEndpoint(s pb.ArmoryServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.RefreshTokenRequest)
		v, err := s.RefreshToken(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeListMyMessagesEndpoint(s pb.ArmoryServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.ListMyMessagesRequest)
		v, err := s.ListMyMessages(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeListMyTasksEndpoint(s pb.ArmoryServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.ListMyTasksRequest)
		v, err := s.ListMyTasks(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeGetSlicerResourcesEndpoint(s pb.ArmoryServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.GetSlicerResourcesRequest)
		v, err := s.GetSlicerResources(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeListUserDevicesEndpoint(s pb.ArmoryServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.ListUserDevicesRequest)
		v, err := s.ListUserDevices(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeGetPrintStatusEndpoint(s pb.ArmoryServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.GetPrintStatusRequest)
		v, err := s.GetPrintStatus(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeGetTtcodeEndpoint(s pb.ArmoryServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.GetTtcodeRequest)
		v, err := s.GetTtcode(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

// WrapAllExcept wraps each Endpoint field of struct Endpoints with a
// go-kit/kit/endpoint.Middleware.
// Use this for applying a set of middlewares to every endpoint in the service.
// Optionally, endpoints can be passed in by name to be excluded from being wrapped.
// WrapAllExcept(middleware, "Status", "Ping")
func (e *Endpoints) WrapAllExcept(middleware endpoint.Middleware, excluded ...string) {
	included := map[string]struct{}{
		"Login":              struct{}{},
		"RefreshToken":       struct{}{},
		"ListMyMessages":     struct{}{},
		"ListMyTasks":        struct{}{},
		"GetSlicerResources": struct{}{},
		"ListUserDevices":    struct{}{},
		"GetPrintStatus":     struct{}{},
		"GetTTCode":          struct{}{},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc, _ := range included {
		if inc == "Login" {
			e.LoginEndpoint = middleware(e.LoginEndpoint)
		}
		if inc == "RefreshToken" {
			e.RefreshTokenEndpoint = middleware(e.RefreshTokenEndpoint)
		}
		if inc == "ListMyMessages" {
			e.ListMyMessagesEndpoint = middleware(e.ListMyMessagesEndpoint)
		}
		if inc == "ListMyTasks" {
			e.ListMyTasksEndpoint = middleware(e.ListMyTasksEndpoint)
		}
		if inc == "GetSlicerResources" {
			e.GetSlicerResourcesEndpoint = middleware(e.GetSlicerResourcesEndpoint)
		}
		if inc == "ListUserDevices" {
			e.ListUserDevicesEndpoint = middleware(e.ListUserDevicesEndpoint)
		}
		if inc == "GetPrintStatus" {
			e.GetPrintStatusEndpoint = middleware(e.GetPrintStatusEndpoint)
		}
		if inc == "GetTTCode" {
			e.GetTtcodeEndpoint = middleware(e.GetTtcodeEndpoint)
		}
	}
}

// LabeledMiddleware will get passed the endpoint name when passed to
// WrapAllLabeledExcept, this can be used to write a generic metrics
// middleware which can send the endpoint name to the metrics collector.
type LabeledMiddleware func(string, endpoint.Endpoint) endpoint.Endpoint

// WrapAllLabeledExcept wraps each Endpoint field of struct Endpoints with a
// LabeledMiddleware, which will receive the name of the endpoint. See
// LabeldMiddleware. See method WrapAllExept for details on excluded
// functionality.
func (e *Endpoints) WrapAllLabeledExcept(middleware func(string, endpoint.Endpoint) endpoint.Endpoint, excluded ...string) {
	included := map[string]struct{}{
		"Login":              struct{}{},
		"RefreshToken":       struct{}{},
		"ListMyMessages":     struct{}{},
		"ListMyTasks":        struct{}{},
		"GetSlicerResources": struct{}{},
		"ListUserDevices":    struct{}{},
		"GetPrintStatus":     struct{}{},
		"GetTTCode":          struct{}{},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc, _ := range included {
		if inc == "Login" {
			e.LoginEndpoint = middleware("Login", e.LoginEndpoint)
		}
		if inc == "RefreshToken" {
			e.RefreshTokenEndpoint = middleware("RefreshToken", e.RefreshTokenEndpoint)
		}
		if inc == "ListMyMessages" {
			e.ListMyMessagesEndpoint = middleware("ListMyMessages", e.ListMyMessagesEndpoint)
		}
		if inc == "ListMyTasks" {
			e.ListMyTasksEndpoint = middleware("ListMyTasks", e.ListMyTasksEndpoint)
		}
		if inc == "GetSlicerResources" {
			e.GetSlicerResourcesEndpoint = middleware("GetSlicerResources", e.GetSlicerResourcesEndpoint)
		}
		if inc == "ListUserDevices" {
			e.ListUserDevicesEndpoint = middleware("ListUserDevices", e.ListUserDevicesEndpoint)
		}
		if inc == "GetPrintStatus" {
			e.GetPrintStatusEndpoint = middleware("GetPrintStatus", e.GetPrintStatusEndpoint)
		}
		if inc == "GetTTCode" {
			e.GetTtcodeEndpoint = middleware("GetTTCode", e.GetTtcodeEndpoint)
		}
	}
}
